theme:  jekyll-theme-cayman #jekyll-theme-minimal
//title: Brkda
title: <div style="display: flex; align-items: center; justify-content: center; gap: 10px;"><img src="/cosmic2.png" alt="logo" style="height: 40px;"> <span>Brkda</span></div>

description: Gaming and Leisure

# cosmic2.png
# theme: jekyll-theme-minimal
# title: Brkda's Homepage
# description: Landing page for the Brkda Gaming App
# layout: default
# github:
#   is_project_page: false  # This removes the sidebar
