theme:  jekyll-theme-cayman #jekyll-theme-minimal
title: Brkda's Homepage
description: Landing page for the Brkda Gaming App
logo: /assets/img/brkda-logo.png

# theme: jekyll-theme-minimal
# title: Brkda's Homepage
# description: Landing page for the Brkda Gaming App
# layout: default
# github:
#   is_project_page: false  # This removes the sidebar
